  { _id: '573b4624ca9bd0c413022cbb',                                                                                                            
    building: '345_Park',                                                                                                                       
    identifier1: '192.168.2.96',                                                                                                                
    identifier2: '1',                                                                                                                           
    identifier3: '40166',                                                                                                                       
    identifier4: '17',                                                                                                                          
    identifier5: '1',                                                                                                                           
    name: 'Voltage-VLN-A',                                                                                                                      
    resource: 'voltage',                                                                                                                        
    source: 'pq_meter',                                                                                                                         
    units: 'V',                                                                                                                                 
    status: 'pending configuration',                                                                                                            
    hidden: false,                                                                                                                              
    dis: 'Voltage-VLN-A' }